name:                EulerHS
version:             0.0.1.0
github:              "https://bitbucket.org/juspay/euler-ps"
license:             Private
author:              "Juspay Technologies Pvt Ltd"
copyright:           "Juspay Technologies Pvt Ltd 2019"

default-extensions:
- NoImplicitPrelude
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- errors
- extra
- hashable
- mtl
- network
- optparse-applicative
- text
- transformers
- unordered-containers
- lens
- http-client
- messagepack
- cereal
- time
- newtype
- monad-loops
- http-types
- attoparsec
- scientific
- stm
- named
- tagged
- aeson-pretty
- cryptonite
- process
- vector
- random
- free
- async
- haskeline
- bytestring-conversion
- universum
- fmt
- lens-aeson
- uuid
- safe-exceptions
- newtype-generics

library:
  source-dirs:
    - src
  ghc-options:
  - -Wall

executables:
  credit-platform:
    main:                Main.hs
    source-dirs:         app/credit_platform
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts
    dependencies:
    - EulerHS
