---
resolver: lts-15.15

packages:
  - .

extra-deps:
  - git: https://github.com/juspay/hedis
    commit: 4ea54f16c0057acc99a9f0e9b63ea51ea4bf420e
  - git: https://github.com/juspay/beam-mysql
    commit: 7960580e041188459cfafef9c49aa6535ef4243e
  - git: https://github.com/juspay/beam
    commit: b626c85f4d86b0960359d8b99613a9a0439667a2
    subdirs:
      - beam-core
      - beam-migrate
      - beam-sqlite
      - beam-postgres
  # Needed for beam
  - dependent-map-0.4.0.0@sha256:ca2b131046f4340a1c35d138c5a003fe4a5be96b14efc26291ed35fd08c62221,1657
  - dependent-sum-0.7.1.0@sha256:5599aa89637db434431b1dd3fa7c34bc3d565ee44f0519bfbc877be1927c2531,2068
  - haskell-src-exts-1.21.1@sha256:11d18ec3f463185f81b7819376b532e3087f8192cffc629aac5c9eec88897b35,4541
  - sqlite-simple-0.4.18.0@sha256:3ceea56375c0a3590c814e411a4eb86943f8d31b93b110ca159c90689b6b39e5,3002
  - constraints-extras-0.3.0.2@sha256:bf6884be65958e9188ae3c9e5547abfd6d201df021bff8a4704c2c4fe1e1ae5b,1784
  - direct-sqlite-2.3.26@sha256:04e835402f1508abca383182023e4e2b9b86297b8533afbd4e57d1a5652e0c23,3718
# MySQL
# MacOS:
# Problem: MacOS build failure
# >   Configuring mysql-0.1.7...
# >   setup: Missing dependencies on foreign libraries:
# >   * Missing (or bad) C libraries: ssl, crypto
# Possible solution:
# https://github.com/depressed-pho/HsOpenSSL/issues/41
# TODO: how to make it portable?
extra-include-dirs:
  - /usr/local/opt/openssl/include
extra-lib-dirs:
  - /usr/local/opt/openssl/lib

# Linux:
# sudo apt install mysql-client
# sudo apt-get install libmysqlclient-dev

nix:
  enable: false
  packages: [mysql57, openssl, zlib, postgresql]
