name:                euler-backend
version:             0.9.0.0
github:              "https://bitbucket.org/juspay/euler-hs"
license:             OtherLicense
author:              "Juspay Technologies Pvt Ltd"
copyright:           "Juspay Technologies Pvt Ltd 2019"

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFunctor
- DeriveGeneric
- DuplicateRecordFields
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-casing
- base16-bytestring
- binary
- base16-bytestring
- bytestring
- comonad
- containers
- errors
- euler-hs
- euler-backend-storage
- extra
- hashable
- HUnit
- mtl
- network
- optparse-applicative
- text
- transformers
- unordered-containers
- lens
- generic-deriving
- http-client
- http-client-tls
- messagepack
- cereal
- time
- newtype
- monad-loops
- http-types
- attoparsec
- scientific
- stm
- named
- tagged
- aeson-pretty
- cryptonite
- process
- vector
- random
- free
- async
- haskeline
- bytestring-conversion
- universum
- fmt
- lens-aeson
- uuid
- safe-exceptions
- newtype-generics
- servant
- servant-server
- servant-client
- servant-swagger
- servant-docs
- wai
- warp
- servant-xml
- xmlbf
- xmlbf-xeno
- natural-transformation
- semigroupoids
- generic-lens
- validation
- http-api-data
- directory
- timeit
- prometheus-client
- web-service
- wai-extra
- memory
- cryptonite
- basement
- x509
- x509-store
- cryptostore
- base64-bytestring
- beam-core
- beam-postgres
- beam-sqlite
- beam-mysql
- beam-migrate
- template-haskell
- hedis
- amazonka
- amazonka-core
- amazonka-kms
- raw-strings-qq

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -fhide-source-paths

executables:
  euler-backend:
    main:                EulerBackend.hs
    source-dirs:         app/
    ghc-options:
    - -main-is EulerBackend
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-A32M
    - -with-rtsopts=-AL128M
    - -with-rtsopts=-qn2
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts
    dependencies:
    - euler-backend

  euler-backend-loadtest:
    main:                LoadTest.hs
    source-dirs:         app/
    ghc-options:
    - -main-is LoadTest
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts
    dependencies:
    - euler-backend

tests:
  hspec:
    main: Main.hs
    source-dirs: test
    dependencies:
    - euler-backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - mysql
    - random-strings
    - utf8-string
    - base16-bytestring
    - base64-bytestring
