name:                euler-backend
version:             0.0.1.0
github:              "https://bitbucket.org/juspay/euler-hs"
license:             OtherLicense
author:              "Juspay Technologies Pvt Ltd"
copyright:           "Juspay Technologies Pvt Ltd 2019"

default-extensions:
- NoImplicitPrelude
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- FunctionalDependencies
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- DuplicateRecordFields
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-casing
- bytestring
- containers
- errors
- euler-hs
- extra
- hashable
- mtl
- network
- optparse-applicative
- text
- transformers
- unordered-containers
- lens
- http-client
- http-client-tls
- messagepack
- cereal
- time
- newtype
- monad-loops
- http-types
- attoparsec
- scientific
- stm
- named
- tagged
- aeson-pretty
- cryptonite
- process
- vector
- random
- free
- async
- haskeline
- bytestring-conversion
- universum
- fmt
- lens-aeson
- uuid
- safe-exceptions
- newtype-generics
- servant
- servant-server
- servant-client
- servant-swagger
- servant-docs
- wai
- warp
- servant-xml
- xmlbf
- xmlbf-xeno
- natural-transformation
- semigroupoids
- generic-lens
- validation
- http-api-data
- directory
- timeit
- prometheus-client
- web-service
- wai-extra
- memory
- cryptonite
- basement
- x509
- x509-store
- cryptostore
- beam-core
- beam-postgres
- beam-sqlite
- beam-mysql
- beam-migrate

library:
  source-dirs:
    - src

executables:
  euler-backend:
    main:                Main.hs
    source-dirs:         src/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts

  euler-backend-loadtest:
    main:                LoadTest.hs
    source-dirs:         src/
    ghc-options:
    - -main-is LoadTest
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts

tests:
  hspec:
    main: Main.hs
    source-dirs: test
    dependencies:
    - euler-backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - random-strings
    - utf8-string
    - base16-bytestring
    - base64-bytestring
