name:                console
version:             0.0.1.0
github:              "https://bitbucket.org/juspay/euler-hs"
license:             OtherLicense
author:              "Juspay Technologies Pvt Ltd"
copyright:           "Juspay Technologies Pvt Ltd 2019"

default-extensions:
- NoImplicitPrelude
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- GeneralizedNewtypeDeriving
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- FunctionalDependencies
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- DuplicateRecordFields
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- bytestring
- dashboard
- dhall
- directory
- filepath
- hedis
- jwt
- mtl
- prometheus-client
- servant
- servant-server
- text
- transformers
- universum
- wai
- wai-cors
- warp
- wai-middleware-prometheus

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -O2

executables:
  console:
    main:                Main.hs
    source-dirs:         src/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts

  console-gen-ps:
    main:                GeneratePS.hs
    source-dirs:         gen/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts
    dependencies:
    - dashboard
    - purescript-bridge

tests:
  tasty:
    main: Main.hs
    source-dirs: test
    dependencies:
    - http-client
    - hspec
    - iso8601-time
    - servant-client
    - tasty
    - tasty-hspec
    - tasty-hunit
    - warp
    - console
